@extends('layouts.master')

@section('main-content')
    <!-- Page Heading -->
    <div class="d-flex justify-content-between align-items-center">
        <h1 class="h3 mb-4 text-gray-800"><i class="fa fa-list"></i> AAN</h1>
        <a href="{{ route('admin.users.index') }}" class="btn btn-primary btn-sm"><i class="fa fa-list"></i> List of Users</a>
    </div>
    <div class="row mb-2">
        <div class="col-md-12">
            <div class="card card-body  shadow-sm">
                <form action="{{ route('admin.aan.store') }}" method="POST">
                    @csrf
                    <div class="alert alert-info">Good day, {{ auth()->guard('admin')->user()->full_name }} ! Please generate AAN only for users with notarized contracts and complete requirements. Thank you!</div>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Generated AAN goes here" value="{{ session('aan') ?? ''}}">
                        <div class="input-group-append">
                            <button class="btn btn-primary"><i class="fa fa-bolt"></i> Generate</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="alert alert-warning d-flex align-items-center">
        <i class="fa fa-exclamation-circle"></i>
    <div class="px-2">
    Below is a list of all generated AAN's and the accounts associated with each of them. Please consider generating back-up data for the files every now and then.
        </div>
    </div>
    <table id="aan_table" class="table table-striped  table-bordered w-100">
        <thead>
            <tr>
                <th>ID</th>
                <th>Generated By</th>
                <th>AAN</th>
                <th>Name</th>
                <th>Email</th>
                <th>Date Created</th>
                <th>Status</th>
                <td>Option</td>
            </tr>
        </thead>
        <tbody>
            @php 
                $count = 1;
            @endphp
            @foreach($aans as $aan)
            <tr>
                <td>
                    {{ $count++ }}
                </td>
                <td>
                    {{ $aan->admin->full_name }}
                </td>
                <td>
                    {{ $aan->complete }}
                </td>
                <td>
                    {{ $aan->user->full_name ??'Undefined' }}
                </td>
                <td>
                    {{ $aan->user->email ??'Undefined'}}
                </td>
                <td>
                    {{ $aan->created_at }}
                </td>
                <td>
                    @if($aan->active)
                        <i class="fa fa-check-circle text-success"></i> Active
                    @else
                        <i class="fa fa-check-circle text-secondary"></i> InActive
                    @endif
                </td>
                <td class="text-center d-print-none">
                    <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#delete-modal-{{ $aan->id }}"><i class="fa fa-times"></i> Delete</button>
                    <div class="modal fade" id="delete-modal-{{ $aan->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel"><i class="fa fa-trash"></i> {{ $aan->complete }}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body d-print-none">
                            <form action="{{ route('admin.aan.destroy', $aan->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <div class="alert alert-warning d-flex align-items-center">
                                    <i class="fa fa-exclamation-circle"></i>
                                    <div class="px-2 text-left d-print-none">
                                        Deleting AAN {{ $aan->complete }} will render the account associated with it inactive. Please confirm if you wish to proceed.
                                    </div>
                                </div>
                                <input type="password" required name="password" placeholder="Administrator password" class="form-control">
                                <div class="form-group mt-2 text-right">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                    <button type="submit" class="btn btn-primary">Proceed</button>
                                </div>
                            </form>
                        </div>
                        </div>
                    </div>
                    </div>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
@endsection
@section('top')
    <link rel="stylesheet" href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">

@endsection
@section('bottom')
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.colVis.min.js"></script>
    <script>
        $(function(){
            $('#aan_table').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf','colvis'
        ],
    });
        $('button').addClass('.btn')
        })
    </script>
@endsection
