<?php

namespace App\Nova;

use App\Nova\Actions\GenerateNewAan;
use App\User;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\Boolean;
use Laravel\Nova\Fields\Text;

class Aan extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\AAN::class;

    public static function authorizedToCreate(Request $request)
    {
        return false;
    }

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'id';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [

            Boolean::make('Active', function ($request) {
                return $request->user;
            }),

            Text::make('Owner', function ($request) {
                $hasuser = $request->user;
                if (!$hasuser) {
                    return null;
                }

                $user = User::find($request->user->id);
                return $user ? $user->full_name : null;
            }),

            Text::make('Complete')
                ->exceptOnForms(),

            Text::make('Generated By', function ($request) {
                return User::find($request->admin_id)->full_name;
            }),

            Text::make('Generated Date', function ($request) {
                return $request->created_at->format('m-d-Y');
            }),
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function cards(Request $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function lenses(Request $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [
            (new GenerateNewAan())->standalone(),
        ];
    }

    public static $group = 'User Management';

    public static function label()
    {
        return 'AAN';
    }
}
